name: craftreel-example
version: 1.0
main: dev.tommyjs.craftreelexample.CraftReelExamplePlugin
api-version: 1.8
depend: [packetevents]
commands:
  reelrecord:
    description: Start/stop recording the 4x4 chunk area around you to a .reel file.
    usage: /reelrecord [name]
  reelplay:
    description: Join/leave a looping replay of a .reel file.
    usage: /reelplay [name]
